services:
  positions-store:
    build:
      context: ./saxo/Testovanie
      dockerfile: Dockerfile
    container_name: saxo-positions-prod
    volumes:
      - positions_data:/data
    ports:
      - "8090:8090"
    restart: unless-stopped

  token-daemon-demo:
    build:
      context: ./saxo/Testovanie
      dockerfile: Dockerfile
    container_name: saxo-token-demo
    environment:
      - SAXO_ENV=sim
      - SAXO_CLIENT_ID=2d7a66918b594af5bc2ac830a3b79d2c
      - SAXO_CLIENT_SECRET=2f5ad858c3eb4ee9b5207d9be5c9c8c5
      - TOKENS_FILE=/data/tokens_demo.json
    volumes:
      - demo_tokens:/data
    command: ["python3", "token_daemon.py"]
    restart: unless-stopped

  token-daemon-live:
    build:
      context: ./saxo/Testovanie
      dockerfile: Dockerfile
    container_name: saxo-token-live
    environment:
      - SAXO_ENV=live
      - SAXO_CLIENT_ID=2d7a66918b594af5bc2ac830a3b79d2c
      - SAXO_CLIENT_SECRET=2f5ad858c3eb4ee9b5207d9be5c9c8c5
      - TOKENS_FILE=/data/tokens_live.json
    volumes:
      - live_tokens:/data
    command: ["python3", "token_daemon.py"]
    restart: unless-stopped

  token-proxy-demo:
    build:
      context: ./saxo
      dockerfile: Dockerfile
    container_name: saxo-proxy-demo
    environment:
      - TOKENS_FILE=/data/tokens_demo.json
      - PROXY_HOST=0.0.0.0
      - PROXY_PORT=8080
    volumes:
      - demo_tokens:/data
    ports:
      - "8080:8080"
    command: ["python3", "token_proxy.py"]
    restart: unless-stopped
    depends_on:
      - token-daemon-demo

  token-proxy-live:
    build:
      context: ./saxo
      dockerfile: Dockerfile
    container_name: saxo-proxy-live
    environment:
      - TOKENS_FILE=/data/tokens_live.json
      - PROXY_HOST=0.0.0.0
      - PROXY_PORT=8081
    volumes:
      - live_tokens:/data
    ports:
      - "8081:8081"
    command: ["python3", "token_proxy.py"]
    restart: unless-stopped
    depends_on:
      - token-daemon-live

volumes:
  positions_data:
  demo_tokens:
  live_tokens:
